# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ddeeaf04a4259db299d6aec8fa213f88571f3460f9e1dc29bacfc6953ef523c5dc7982e0257d3b70ab38c27b0cee0561a2a58b7fc4bf1f8ec5dfc601ee10252

test:
  secret_key_base: 6516344785e84b9004d7258693be3fbdeed33a52b3919464234e9b618d4495e2cb85edd2891e60f563db7790f5286c4484834b4ae588a76878a0a6a5f1d18599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
